import sourcer


def main():
    with open('grammar.txt') as f:
        src = f.read()

    g = sourcer.Grammar(src, include_source=True)

    with open('exemplary/parser.py', 'w') as f:
        f.write('# Generated by sourcer, using the command `make parser`\n\n')
        f.write(g._source_code)


if __name__ == '__main__':
    main()
